# Generated by Django 4.2.2 on 2023-06-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0001_initial'),
        ('m_producto', '0002_venta_det_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_compra',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_venta.venta'),
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
