# Generated by Django 4.2.2 on 2023-07-05 20:15

from django.db import migrations, models
import m_producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('m_producto', '0004_delete_det_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=400)),
                ('duracion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('foto', models.ImageField(default=m_producto.models.default_foto, upload_to='img/')),
            ],
        ),
    ]
