# Generated by Django 4.2.2 on 2023-07-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_producto', '0007_alter_viaje_duracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
