# Generated by Django 4.2.2 on 2023-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0002_carrito_itemcarrito_det_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_compra',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='det_compra',
            name='total_com',
        ),
        migrations.AddField(
            model_name='det_compra',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='det_compra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
