# Generated by Django 4.2.2 on 2023-07-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_producto', '0006_alter_producto_nombre'),
        ('m_venta', '0006_remove_productoventa_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='titulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_producto.viaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoventa',
            name='titulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_producto.viaje'),
            preserve_default=False,
        ),
    ]
