# Generated by Django 4.2.2 on 2023-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_producto', '0006_alter_producto_nombre'),
        ('m_venta', '0007_remove_itemcarrito_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoVenta',
            new_name='ViajeVenta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_cant',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
