# Generated by Django 4.2.2 on 2023-07-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0008_rename_productoventa_viajeventa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='titulo',
            new_name='viaje',
        ),
    ]
