# Generated by Django 4.2.2 on 2023-07-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0009_rename_titulo_itemcarrito_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='viajeventa',
            name='cantidad',
        ),
    ]
